### ISSUE TITLE
CORS on WOFF files

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-com-website#143]
Current website is throwing an error on remote (textpattern.io) WOFFs:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://textpattern.io/assets/fonts/pt-serif-v9-latin-ext-700.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

```
downloadable font: download failed (font-family: "PT Serif" style:normal weight:bold stretch:normal src index:0): bad URI or cross-site access not allowed source: https://textpattern.io/assets/fonts/pt-serif-v9-latin-ext-700.woff2
```

This might be restricted to Tor browser as I use that a cache-busting tool. New site build-in-progress has allowances for remote fonts (see https://github.com/textpattern/server-config/blob/master/tractor.textpattern.com/etc/nginx/sites-available/www-dev.textpattern.com.conf#L179 for current incarnation), and yet it throws the same error.

![screen shot 2018-08-29 at 19 54 05](https://user-images.githubusercontent.com/226578/44809217-fc06a100-abc5-11e8-8d8f-8e60c5c20135.png)

Edit: most straightforward solution would be to live with this until www.textpattern.com testing on new server has concluded, and move the files into the www.textpattern.com directory tree rather than www.textpattern.io

**Comment by philwareham** [comment]
I think this is also related to the staging code looking for css/assets at the .com URL - should be ok when properly live.
