### ISSUE TITLE
Homepage animation - scaling issues on some browsers

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#144]
Reported by users:

___
Hello Phil,

tried textpattern.com with a new phone (Moto X4, 1920x1080, Android 8.0) and the background picture is not in the right size, means wider than the screen size. Tested it with
Chrome, Opera and Lightning.
If you need it, I can provide you with a screen shot.
___
While testing on my phone I saw that in Opera Mobile the waving sunflower graphic isn’t scaled down (rather a hint for Phil). The effect is an essentially white page with only the logo, search field, and the hamburger icon at the top. The only browser I saw it like that, BTW.
___

Reference screenshots:

![screenshot_20180523-221350](https://user-images.githubusercontent.com/413665/44902765-be5b6280-ad02-11e8-8d28-ac5c3e118d6c.png)
![opera_mini_landscape-fullscreen-zoomed_out](https://user-images.githubusercontent.com/413665/44902766-be5b6280-ad02-11e8-8fad-bb6e3dc5c7fb.png)
![opera_mini_portrait](https://user-images.githubusercontent.com/413665/44902767-be5b6280-ad02-11e8-9ca3-0fb845bd7a26.png)

**Comment by petecooper** [comment]
https://caniuse.com/#feat=canvas

See note 2: `Opera Mini supports the canvas element, but is unable to play animations or run other more complex applications.`
