### ISSUE TITLE
Revert back to GitHub API via PHP Curl

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#147]
Now our new server is TLSv1.2+ compliant, we can Curl request the GitHub API in PHP again (as I used to do before GitHub shut off access lower than TLSv1.2).

**Comment by philwareham** [comment]
Done. Closing.

**Comment by philwareham** [comment]
@petecooper I *think* you can remove the GitHub API from CSP now as it's fetched by the server now, not by users.

**Comment by petecooper** [comment]
OK, give me ten minutes and I'll make that change.

**Comment by philwareham** [comment]
@petecooper Ta! Looks like something is up with caching at the moment - is this a known issue? See latest Pingdom Tools report (this seemed fine yesterday).

![grab](https://user-images.githubusercontent.com/413665/45018412-f4118b80-b021-11e8-8bc3-cd32e517cc4a.png)

**Comment by petecooper** [comment]
Yes, caching isn’t working properly but I think I’ve fixed it - try again in 5 mins.

-- 
Pete Cooper
pete@pragmatika.net
https://pragmatika.net

**Comment by petecooper** [comment]
OK, I've removed the GitHub API from CSP and re-enabled caching (though I'm not 100% sure it's working correctly).

**Comment by philwareham** [comment]
Boom! Looking good, dude!...

Homepage report:

![grab](https://user-images.githubusercontent.com/413665/45019007-24a5f500-b023-11e8-9d17-2057527a6f35.png)

Blog landing page report:

![grab2](https://user-images.githubusercontent.com/413665/45019029-325b7a80-b023-11e8-855d-e571d2972906.png)

**Comment by petecooper** [comment]
Can you sanity checking the expiry headers? I'm seeing a standard 1 month on everything here…which is wrong.

**Comment by philwareham** [comment]
OK, leave the expiry header rules with me, I'll check them against what I had in Apache. I need to read up on the different syntax used for Nginx compared to Apache for these expire rules first.

**Comment by petecooper** [comment]
The rules are set correctly, they're not being implemented properly - I have 
https://github.com/textpattern/server-config/issues/9 as an issue that I can work around with a Plan B.

**Comment by petecooper** [comment]
All fixed.
