### ISSUE TITLE
Plugin redux

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#153]
I'm fairly sure we can replicate functionality of the following plugins...

* rah_sitemap (used to generate sitemap.xml file)
* rah_external_output (used to serve the version.json file that declared current Textpattern releases and betas)

...via the core tags instead.

Reference to investigate:

Sitemap: https://forum.textpattern.io/viewtopic.php?pid=313909#p313909

External JSON: https://github.com/textpattern/textpattern/issues/839#issuecomment-323192632

**Comment by philwareham** [comment]
@petecooper Hiya, I've uploaded new theme files to the Textpattern.com site, can you please fix permissions for those and then do the following Apache equivalent in your Nginx config?:

    RewriteRule ^sitemap.xml$  index.php?s=sitemap [L]

Let me know when that is done and I'll re-import the theme and we can remove the rah_sitemap plugin.

**Comment by philwareham** [comment]
@petecooper I've also amended the code so that version.json is generated by core tags, So can you please also add this Apache equivalent in your Nginx config for this site too, as well as the above?:

    RewriteRule ^version.json$  index.php?s=version [L]

That means we can also remove rah_external_output form our plugins! Thanks again.

**Comment by petecooper** [comment]
@philwareham - this is pretty much ready to go, awaiting `index.php?s=sitemap` to go live (currently 404) and I'll test it, then deploy when ready.

**Comment by petecooper** [comment]
Permissions reset, btw.

**Comment by philwareham** [comment]
Great, ta! I've just imported the latest theme and set up the required sections (sitemap and version). So they are all ready from my side.

**Comment by philwareham** [comment]
Sure, tonight is totally fine. Cheers!

**Comment by philwareham** [comment]
Hi Pete, just wondering if you had any luck with these redirects as yet? Cheers!

**Comment by petecooper** [comment]
Morning @philwareham - one thing left to resolve. Full work week this week so will likely be an evening job, but will get done.

**Comment by philwareham** [comment]
Great - OK thanks for the update. PS. I didn't have time to send those mugs beige holiday, sorry. They are here on my desk packed up ready so I'll drop them at post office tomorrow.

**Comment by philwareham** [comment]
Hi Pete, I know you are busy, but any news on this?

We currently have a broken sitemap and version.json file on the live site without those two redirects.

**Comment by petecooper** [comment]
Crap, I thought I'd fixed this weeks ago. Will look this morning!

**Comment by petecooper** [comment]
Both done, please test (works fine here).
https://textpattern.com/version.json should 301 redirect to https://textpattern.com/index.php?s=version
https://textpattern.com/sitemap.xml should 301 redirect to https://textpattern.com/index.php?s=sitemap

**Comment by petecooper** [comment]
PS: sorry for the delay in getting this done!

**Comment by philwareham** [comment]
Thanks Pete, but is there any way of doing it so it doesn't actually change the URL (not sure what the technical name for that is).

If not, then not a big problem I guess.

**Comment by petecooper** [comment]
I'm looking into that at the moment - I'm sure there is. Leave this open for now, to be continued.

**Comment by petecooper** [comment]
Done and done.

![screen shot 2018-11-06 at 00 17 53](https://user-images.githubusercontent.com/226578/48034983-87b62400-e159-11e8-843d-dc0eee8d346c.png)
![screen shot 2018-11-06 at 00 18 07](https://user-images.githubusercontent.com/226578/48034984-87b62400-e159-11e8-8a0a-d66723d4d61f.png)

**Comment by philwareham** [comment]
Great stuff! Thank you Pete.
