### ISSUE TITLE
SCSS does not build on Windows

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern-com-website#2]
```grunt compass:dev``` throws this error:

```
Sass::SyntaxError on line ["7"] of C: Invalid Windows-1252 character "\xC3"
```

This is caused by an [open issue with Singularity 1.6.2](https://github.com/at-import/Singularity/issues/207).

**Comment by rwetzlmayr** [comment]
Workaround: Use a shell with a UTF-8 code page. like so:

```
chcp 65001
```

**Comment by philwareham** [comment]
Thanks Robert, I'll keep an eye open for a new release of Singularity and update as soon as it's available.
