### ISSUE TITLE
Consider dropping AMP

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#215]
AMP is a Google proprietary technology that is generally accepted as bad for the future health of the web and publishers. We should consider removing it from our blog posts, even if it causes a drop in search traffic (debatable).

Please list any objections or agreement. If I don't hear anything that sways me in the next 2 weeks I will remove the code.

**Comment by wion** [comment]
Pull the AMP's plug!

**Comment by petecooper** [comment]
Note: if this does get zapped, we can remove `pat_if_amp` from the plugins list.

**Comment by petecooper** [comment]
Bump.

**Comment by philwareham** [comment]
OK, leave it with me! :)

**Comment by philwareham** [comment]
It's gone. Don't be evil, Google.
