### ISSUE TITLE
Use file description to house checksum

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern-com-website#281]
Could we store the checksum in the File Description field and then pull that out automatically when building the links to the downloads on the release blog posts and _get started_ pages? Seems like that would avoid some unnecessary steps during the release process and means we don't have to manually keep everything in sync on the site.

Any downsides?

**Comment by philwareham** [comment]
Sure. I'll do that when I get some spare time.

**Comment by Bloke** [comment]
Nice one, Phil, thanks. What are we doing about previous downloads? The descriptions currently house things like 'Zip format.' Are we going to leave those, or back-fill them? If so, I can go through and do that if you like sometime.

**Comment by philwareham** [comment]
I'm just backfilling them now. Although I have a conference call in 15 mins so I'll finish after that.

**Comment by Bloke** [comment]
Ah, I just spotted you doing that and came to apologise for jumping the gun. Thanks again!
