### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by bts368** [textpattern/textpattern-com-website#3]
your HTTPS is broken.

An error occurred during a connection to textpattern.com. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

https://stackoverflow.com/a/4762977

**Comment by philwareham** [comment]
We don't use HTTPS on Textpattern.com at the moment.

**Comment by philwareham** [comment]
FYI Will be moving to HTTPS when the new site launches later this year.

**Comment by philwareham** [comment]
New site in staging is HTTPS, will be launched within the next month, so closing this issue.
