### ISSUE TITLE
user docs: prefers-color-scheme rules?

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern-com-website#327]
phi13 introduced me to this Firefox extension, [dark mode switcher](https://github.com/rugk/website-dark-mode-switcher/), to help me test my `prefers-color-scheme` rules in local dev, because it's the only way I could see the changes with my late 2011 mbp that can't run more than Sierra.

Anyway, when I added the extension, I could then see what the Forum looked like in dark mode on my laptop for the first time, and any other site that uses`prefers-color-scheme`. Then I looked at user docs. :{

Any chance?

I find my aging eyes do a lot better in dark modes anymore. Just looking at this blaring, glaring white github box with small font is a strain.

I suppose I could try the popular [Midnight Lizard](https://addons.mozilla.org/en-US/firefox/addon/midnight-lizard-quantum/) extension, which makes everything dark mode whether a site uses `prefers-color-scheme` or not, but I think I prefer dark mode when it comes from a site intentionally supporting the rules.

**Comment by philwareham** [comment]
I'm not sure what you mean. The whole Textpattern family of sites respect dark mode.

**Comment by wion** [comment]
Hmm. Yes, it works for me on mobile too. I should have confirmed that (or looked at the styles, doh). Which means you are using the rules.

But on my old laptop, I get dark mode for the forum, using the aforementioned plugin, but not for docs. If the style rules are there, it should work for both.

I’m actually out on an errand. I will double check on my laptop when I get back and report.

**Comment by wion** [comment]
In any case this is a moot issue since the rules work for mobile as intended. Closing.

**Comment by wion** [comment]
https://forum.textpattern.com/viewtopic.php?pid=327456#p327456
