### ISSUE TITLE
"Featured at" links are useless

### ISSUE THREAD

**Issue by eliph** [textpattern/textpattern-com-website#329]
**Describe the bug**
The sections "Get started", "Blog" and "About" have some links under the header "Featured at". If you follow these links, you will find that none of them contain any useful information about Textpattern, and some links are dead.

**To reproduce**
Steps to reproduce the behaviour:
1. Go to https://textpattern.com/start/
2. Follow the links listed under "Featured at"
3. Any information about Textpattern, no?

**Expected behaviour**
Links to more informative websites or nothing.

**Comment by philwareham** [comment]
It's a paid-for advert, basically. Not my preference, but it provides a small amount of revenue to keep the lights on.

**Comment by eliph** [comment]
Then it is a "Sponsored Link" and should be labelled as such, and not labelled as "Powered by". It links to mysterious and potentially dangerous websites and discredits the Textpattern project.

**Comment by philwareham** [comment]
Agreed. I have amended this item now, for more transparency, as suggested.
