### ISSUE TITLE
Turn off and remove comments on .com site

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#341]
IMO we should turn off the commenting features and remove the comment templates and specific CSS from our theme (leaving the old comments in the backend but remove the code from templates that actually displays them on live site).

Many existing comments are obsolete, link to dead URLs, or have little value in a modern website. Better that we encourage discussions on the forum or social media where proper back-and-forth dialogue can happen.

@petecooper @bloke thoughts?

**Comment by petecooper** [comment]
+1.

Nothing sadder than an article with zero comments, too.
