### ISSUE TITLE
Web Informer widget causing delay in initial server response

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-com-website#343]
We've ascertained that fetching the HTML for the web informer widget causes around 300ms of lag on the initial server response - pushing us into a non-pass on Core Web Vitals. I'd like to reduce that lag if possible but we can't cache the HTML, for reasons.

Currently the code to fetch this HTML is:

```php
if (!gps('txpreview')) {
    $opts = array('http' => array('timeout' => 1.6));
    $url = 'https://website.informer.com/widget/textpattern.com-2';
    $context = stream_context_create($opts);
    $widget = file_get_contents($url, false, $context);

    if ($widget) {
        echo $widget;
    }
}
```

I'm wondering if there is any performance gain from using `stream_copy_to_stream` instead of `file_get_contents`?

@bloke what do you think, and if so can you give me a pointer on the code needed?

**Comment by Bloke** [comment]
`stream_copy_to_stream()` or, failing that, a homegrown `fgets()` (or equivalent with a streaming context) might well be faster. Usually these things are only of benefit for large files, and this content is nowhere near what anyone would call 'large'. The delay may well be attributable to the round-trip connection rather than streaming, but it's gotta be worth a shot. I'll try a few tests locally and see what happens.

**Comment by philwareham** [comment]
@rwetzlmayr hi Robert, do you know how the above is measured by customer? i.e. Is it based on hits to the endpoint HTML?

I'd like to cache the HTML for a period of time if I can, but not if it is based on direct hits.

**Comment by rwetzlmayr** [comment]
@philwareham I do not know whether this is measured by the customer but I don't think so...

**Comment by philwareham** [comment]
Thanks Robert, I will test some short caching of the HTML (say, 10 minutes) and see if it improves matters.

**Comment by philwareham** [comment]
OK, caching that item speeds the page up massively; was ~560ms, now ~110ms. Happy with that. If we can any kickback from customer I can revisit (but should hopefully be fine).

<img width="801" alt="Screenshot 2021-02-12 at 09 53 53" src="https://user-images.githubusercontent.com/413665/107753975-bc41be80-6d18-11eb-9652-a1a8f46e4c5d.png">
