### ISSUE TITLE
Missing file used in `README.md`: `/assets/img/branding/carver/carver-64px.svg`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-com-website#345]
https://textpattern.com/assets/img/branding/carver/carver-64px.svg

We use the above in https://github.com/textpattern/textpattern/blob/dev/README.md and possibly more, but it's 404-ing at the current time. I've found a copy in a backup, and I've attached a .zip with the entire `carver` directory as-was.

I'm presuming this is part of a recent-ish branding tidy up, so we need to either bake a 64px version (and perhaps derivatives for the other sizes, too) that can be tracked or just drop these back into place.

[carver svg.zip](https://github.com/textpattern/textpattern-com-website/files/5976180/carver.svg.zip)

**Comment by philwareham** [comment]
Fixed, thanks.
