### ISSUE TITLE
Add a `security.txt`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-com-website#353]
https://securitytxt.org

We have no mention of our security policy on the front page, and we're getting more interest in that side of things.

We should consider making and maintaining a sensible security.txt for researchers, and avoid disclosure via a public issue.

**Comment by philwareham** [comment]
OK, not sure what to fill in at that URL so if someone wants to generate the txt file I will link it in the footer of the website(s) - if that's what you want.

**Comment by petecooper** [comment]
Let's start with this:

```
Contact: security@textpattern.com
Expires: Fri, 31 Dec 2021 23:59 +0000
Preferred-Languages: en
Canonical: https://textpattern.com/.well-known/security.txt
```

If you can get the file itself tracked in this repo, I'll make sure we have a copy in `.well-known` and I can tweak it (like adding in .com landing page for security stuff if/when we have one.

**Comment by petecooper** [comment]
We could also handle this as an article on .com, to be fair…leave this with me and I'll tinker later this week.

**Comment by philwareham** [comment]
I've just added the file to the repo (but not uploaded to server) - please use as you see fit and let me know if I need to add links anywhere.

**Comment by petecooper** [comment]
OK, I think I've managed this in an article, so we can zap the security.txt file from here actually. I'll do that now.

https://textpattern.com/security.txt

See article 439 for details. I'll leave this open as a reminder to set up a `.well-known` alias and then close it.

**Comment by petecooper** [comment]
Not sure why this is still open, is done, will close.
