### ISSUE TITLE
AMP version into 'Related Article' links

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern-com-website#82]
Phil.

I think you could add the AMP version of each related articles into the "Latest blog articles" links :

From your article_amp form: https://github.com/textpattern/textpattern-com-website/blob/master/src/templates/forms/article/amp.txp#L83

Change:

`<a href="<txp:permlink />"><txp:title /></a>`

To:

`<a href="<txp:permlink />"><txp:title /><txp:if_variable name="pat_amp" value="1">/amp</txp:if_variable></a>`

**Comment by philwareham** [comment]
Hi.

Do you mean?...

   <a href="<txp:permlink /><txp:if_variable name="pat_amp" value="1">/amp</txp:if_variable>"><txp:title /></a>

**Comment by cara-tm** [comment]
May be :D
